name: proww
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.13.1
  http: ^1.2.2
  flutter_html: ^3.0.0-beta.2
  connectivity_plus: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/Stocks.jpeg"
flutter:

  uses-material-design: true
  assets:
    - assets/images/

